### ISSUE TITLE
Cannot start nuxt:  Cannot read properties of undefined (reading 'as')

### ISSUE THREAD

**Issue by Aikoyori** [nuxt-alt/auth#1]
I am having problems with the library right now.
I switched to Nuxt 3.0.1 (Edge) `Nuxt 3.0.1-rc.0-27845213.4641e8e with Nitro 1.0.1-27841947.ca47a3a` to fix the nuxt/framework#4232

Here is the log file
```log
 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'as')
  at /C:/Users/Aikoyori/somewhere/node_modules/@nuxt-alt/auth/dist/module.mjs:682:31
  at Array.filter (<anonymous>)
  at setup (/C:/Users/Aikoyori/somewhere/node_modules/@nuxt-alt/auth/dist/module.mjs:681:57)
  at async normalizedModule (/C:/Users/Aikoyori/somewhere/node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async installModule (/C:/Users/Aikoyori/somewhere/node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:418:3)
  at async initNuxt (/C:/Users/Aikoyori/somewhere/node_modules/nuxt/dist/index.mjs:1853:7)
  at async load (/C:/Users/Aikoyori/somewhere/node_modules/nuxi/dist/chunks/dev.mjs:6780:9)
  at async Object.invoke (/C:/Users/Aikoyori/somewhere/node_modules/nuxi/dist/chunks/dev.mjs:6841:5)
  at async _main (/C:/Users/Aikoyori/somewhere/node_modules/nuxi/dist/cli.mjs:50:20)

                                                                                                              21:11:02
```

**Comment by Teranode** [comment]
Was this happening in 3.0.0?

**Comment by Aikoyori** [comment]
Due to nuxt/framework#4232 (a bug), I could not reach that point so technically it does not happen.

**Comment by Teranode** [comment]
what does your nuxt config look like?

**Comment by abdullah-life** [comment]
@Teranode You need to change module dependency to nuxt v3.0.0-rc.14 (or whichever version works)

The stable one has a bug. It doesn't allow to start `nuxt dev` on windows.
